### ISSUE TITLE
Client ID case sensitive

### ISSUE THREAD

**Issue by bvangraafeiland** [yfxie/ckeditor-imgur#1]
Hey, thanks for this plugin, it was pretty much exactly what I needed. However, I found a little typo in the readme, it says `config.imgurClientID` but that should be `config.imgurClientId` (lower case D), as that's what the code refers to.

**Comment by djvs** [comment]
I was just about to write this.  Not only is this a problem in the README, the plugin code alert message (clientIdMissing) specifies it in the wrong case too!   Really nasty when you get imgur bundled with your ckeditor.  Had to start grepping across ckeditor's whole folder to even find the problem.

**Comment by djvs** [comment]
@yfxie

**Comment by yfxie** [comment]
@djvs @bastiaan89 fixed the problem, thanks you guys. the latest version is 1.0.2
