### ISSUE TITLE
Fix documentation case problem

### ISSUE THREAD

**Issue by EdOverride** [yfxie/ckeditor-imgur#16]
In documentation you have:
```javascript
config.imgurClientId = ''
```

But the issue is that extension needs `imgurClientID` not `imgurClientId` (notice the case).
I wasted quite a lot of time, cos of this.

Please update the readme

**Comment by yfxie** [comment]
Sorry about this unmaintained project pissed you. I have updated the README. Pull requests are welcome if other issues you can fix. I will appreciate you.

**Comment by EdOverride** [comment]
I didn't want to come across as a rude guy. I'm sorry. :D 
Besides, I didn't see anywhere a mention that the project is unmaintained.
