### ISSUE TITLE
Unable to set it up

### ISSUE THREAD

**Issue by Tibo46** [yfxie/ckeditor-imgur#3]
Hi,

Looks like i am not able to set the imgurClientID working. I am always getting the alert telling me to add the key into the config file : 
![image](https://cloud.githubusercontent.com/assets/3435942/14066824/1986773a-f455-11e5-8d89-5c6a6ae17107.png)

But it is there.
Also, i do not want my user to have all the tools in the toolbar so i created that array :
`config.toolbar = [
        { name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
        { name: 'editing', groups: [ 'find', 'selection', 'spellchecker' ], items: [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
        '/',
        { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat' ] },
        { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-' ] },
        { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
        '/',
        { name: 'styles', items: [ 'Styles', 'FontSize' ] },
        { name: 'colors', items: [ 'TextColor'] },
        { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
        // Here what should i have to add your plugin ?
    ];`
Could you tell me what i could add inside it to add you plugin button into my toolbar?

Kind regards

**Comment by yfxie** [comment]
the `config.js` should be look like following:

```
CKEDITOR.editorConfig = function(config) {
//....
config.extraPlugins = 'youtube,imgur';
config.imgurClientId = 'your client id';
config.toolbar = [
  { name: 'insert', items: [ 'Image', 'Table', 'Smiley', 'SpecialChar', 'Imgur' ] }
  // ...
];
}
```

the key is to add `Imgur` to your items

**Comment by Tibo46** [comment]
Hi,

Thanks for your reply. yes my config.js looks like that :

`CKEDITOR.editorConfig = function( config ) {

```
config.extraPlugins = 'imgur';
config.imgurClientID = 'xxxxxxxxxxxxxxx';
// Define changes to default configuration here. For example:
config.language = 'fr';
config.toolbar = [
    { name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
    { name: 'editing', groups: [ 'find', 'selection', 'spellchecker' ], items: [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
    '/',
    { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat' ] },
    { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-' ] },
    { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
    '/',
    { name: 'styles', items: [ 'Styles', 'FontSize' ] },
    { name: 'colors', items: [ 'TextColor'] },
    { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
    { name: 'insert', items: [ 'Image', 'Imgur' ]}
];};`
```

I can see on my editor the icons for your plugin 
![image](https://cloud.githubusercontent.com/assets/3435942/14150014/47dc7a7c-f6a7-11e5-96df-7bb9ec2d6aa6.png)

but i am still getting the error telling me to add config.imgurClientID into my config.js file.
Maybe i'm missing something?

**Comment by yfxie** [comment]
try to run `bundle update ckeditor-imgur` and see if the version is `1.0.2`
